
simple:
	g++ rabbitBlow.cpp name.cpp -o rabbit-flow.exe -std=c++17 -pedantic-errors

debug:
	g++ rabbitBlow.cpp name.cpp -o rabbit-flow.exe -Wall -Weffc++ -Wextra -Wconversion -pedantic-errors -std=c++17 -O0 -g 

optimize:
	g++ rabbitBlow.cpp name.cpp -o rabbit-flow.exe -Wall -Weffc++ -Wextra -Wconversion -pedantic-errors -std=c++17 -O3 
