
simple:
	g++ rabbitBlow.cpp name.cpp -o rabbit-flow.exe -std=c++20 -pedantic-errors -lboost_system

debug:
	g++ rabbitBlow.cpp name.cpp -o rabbit-flow.exe -Wall -Weffc++ -Wextra -Wconversion -pedantic-errors -std=c++20 -O0 -g -lboost_system

optimize:
	g++ rabbitBlow.cpp name.cpp -o rabbit-flow.exe -Wall -Weffc++ -Wextra -Wconversion -pedantic-errors -std=c++20 -O3 -lboost_system
