
simple:
	g++ rabbitBlow.cpp name.cpp -o rabit-flow.exe -std=c++20 -pedantic-errors

debug:
	g++ rabbitBlow.cpp name.cpp -o rabbit-flow.exe -Wall -Werror -Weffc++ -Wextra -Wconversion -pedantic-errors -std=c++20 -O0 -g

optimize:
	g++ rabbitBlow.cpp name.cpp -o rabbit-flow.exe -Wall -Werror -Weffc++ -Wextra -Wconversion -pedantic-errors -std=c++20 -O3
